import assert from 'node:assert/strict';
import { MemoryStore } from '../src/core/store.js';
import { requireReadMethod } from '../src/core/readPolicies.js';
import { executeApprovedReadPage, MAX_RESPONSE_BYTES } from '../src/core/readPolicy.js';
import { asToolResult, envelope } from '../src/core/respond.js';
import { OzonFinanceChunks } from '../src/core/ozonFinanceChunks.js';
const store=new MemoryStore();
const conn=await store.addConnection({marketplace:'ozon',name:'synthetic finance',status:'active',mock:false,sandbox:false,permissions:['finance.read']},{client_id:'synthetic',api_key:'synthetic'});
const method=requireReadMethod('ozon','GetFinanceAccrualByDay');
const rows=Array.from({length:120},(_,i)=>({accrual_id:String(i),total_amount:{amount:'9007199254740993.01',currency:'RUB'},detail:'я'.repeat(4000)}));
let calls=0;
const transport={async send(input:any){calls++;assert.equal(input.params.mcp_cursor,undefined);return input.params.last_id===''?{accruals:rows,last_id:'page2'}:{accruals:[],last_id:''};}};
let params:Record<string,unknown>={date:'2026-09-30',last_id:''};
const received:any[]=[];
let chunks=0;
do {
  const page=await executeApprovedReadPage({store,marketplace:'ozon',connectionId:conn.connection_id,method,params,transport});
  const packed=asToolResult(envelope(page.payload,{marketplace:'ozon',connectionId:conn.connection_id,continuation:page.continuation}));
  assert(Buffer.byteLength(JSON.stringify({jsonrpc:'2.0',id:1,result:packed}))<MAX_RESPONSE_BYTES);
  received.push(...(page.payload as any).accruals);chunks++;
  if(!page.continuation.has_more)break;
  params={...params,...page.continuation.request_patch};
  if(page.continuation.kind==='last_id'){assert.equal(params.mcp_cursor,null);assert.equal(params.date,'2026-09-30');}
  assert(chunks<100);
}while(true);
assert.deepEqual(received,rows);assert.equal(calls,2);assert(chunks>2);
await assert.rejects(executeApprovedReadPage({store,marketplace:'ozon',connectionId:conn.connection_id,method,params:{date:'2026-09-30',last_id:'',mcp_cursor:'malformed'},transport}),(e:any)=>e.code==='LOCAL_DENY');
assert.equal(calls,2);
const postings=requireReadMethod('ozon','GetFinanceAccrualPostings');
await assert.rejects(executeApprovedReadPage({store,marketplace:'ozon',connectionId:conn.connection_id,method:postings,params:{posting_numbers:[]},transport}),(e:any)=>e.code==='LOCAL_DENY');
assert.equal(calls,2);
let clock=0;const cache=new OzonFinanceChunks(()=>clock);
const first=cache.split({accruals:rows,last_id:'next'},{kind:'last_id',has_more:true,request_patch:{last_id:'next'}},'binding',conn.connection_id,{date:'2026-09-30',last_id:''});
const token=first.continuation.request_patch!.mcp_cursor;
assert.deepEqual(cache.resume(token,'binding'),cache.resume(token,'binding'),'idempotent retries');
assert.throws(()=>cache.resume(token,'other-account'),(e:any)=>e.code==='LOCAL_DENY');
clock=10*60*1000;
assert.throws(()=>cache.resume(token,'binding'),(e:any)=>e.code==='STALE_DATA'&&e.opts.retryable===true);
assert.throws(()=>cache.split({accruals:[{detail:'x'.repeat(300000)}],last_id:''},{kind:'last_id',has_more:false,request_patch:null},'binding',conn.connection_id,{date:'2026-09-30'}),(e:any)=>e.code==='BULK_LIMIT_EXCEEDED');
const before=calls;
await executeApprovedReadPage({store,marketplace:'ozon',connectionId:conn.connection_id,method,params:{date:'2026-09-30',last_id:'page2'},transport});assert.equal(calls,before+1);
console.log('PASS lossless finance chunks, complete MCP ceiling, upstream transition, cursor denial, postings minItems; WRITE_REQUESTS_SENT=0');
