import assert from 'node:assert/strict';
import { resolveOzonFile,isPublicOzonFileAddress } from '../src/adapters/ozon/download.js';
import { findDownload } from '../src/core/fileCache.js';
import { readOzonResponse } from '../src/adapters/ozon/boundedResponse.js';
for(const address of ['127.0.0.1','10.1.2.3','169.254.169.254','172.16.0.1','192.168.0.1','100.64.0.1','198.18.0.1','::1','::ffff:127.0.0.1'])assert.equal(isPublicOzonFileAddress(address),false,address);
assert.equal(isPublicOzonFileAddress('93.184.216.34'),true);
let dnsCalls=0;
const resolver:any=async()=>{dnsCalls++;return [{address:'93.184.216.34',family:4}];};
for(const value of ['https://example.invalid/file','https://evil.ozone.ru/file','http://ir.ozone.ru/file','https://user:synthetic@ir.ozone.ru/file','https://ir.ozone.ru:8443/file'])await assert.rejects(resolveOzonFile(new URL(value),resolver),(e:any)=>e.code==='LOCAL_DENY');
assert.equal(dnsCalls,0);
assert.equal(await resolveOzonFile(new URL('https://ir.ozone.ru/synthetic'),resolver),'93.184.216.34');
await assert.rejects(resolveOzonFile(new URL('https://ir.ozone.ru/synthetic'),(async()=>[{address:'127.0.0.1',family:4}]) as any),(e:any)=>e.code==='LOCAL_DENY');
console.log('PASS Ozon file HTTPS/host/port/userinfo and private-DNS denial; checked address pinned; no live download');
assert.deepEqual(findDownload({result:{file:'https://ir.ozone.ru/synthetic'}},true),{url:'https://ir.ozone.ru/synthetic'});
assert.equal(findDownload({result:{file:'https://ir.ozone.ru/synthetic'}}),null,'other marketplaces unchanged');
assert.equal((await readOzonResponse(new Response('1234'),4)).toString(),'1234');
await assert.rejects(readOzonResponse(new Response('12345'),4),(e:any)=>e.code==='BULK_LIMIT_EXCEEDED');
await assert.rejects(readOzonResponse(new Response('12345',{headers:{'content-length':'5'}}),4),(e:any)=>e.code==='BULK_LIMIT_EXCEEDED');
console.log('PASS documented report file field and bounded chunk/header sizes');
