import assert from 'node:assert/strict';
import { contracts,diffContracts } from '../scripts/ozon-spec-diff.mjs';
const spec={openapi:'3.0.0',paths:{'/synthetic':{post:{operationId:'same',requestBody:{content:{'application/json':{schema:{$ref:'#/components/schemas/Node'}}}},responses:{'200':{content:{'application/json':{schema:{allOf:[{$ref:'#/components/schemas/Node'},{oneOf:[{type:'string'},{type:'null'}]}]}}}}}}}},components:{schemas:{Node:{type:'object',required:['id'],properties:{id:{type:'string'},child:{$ref:'#/components/schemas/Node'}}}}}};
const before=contracts(spec,'seller');
assert.equal(before.length,1);
assert.deepEqual(before[0].contract.refs['#/components/schemas/Node'],spec.components.schemas.Node,'recursive reference preserved without truncation');
const changed=structuredClone(spec);changed.components.schemas.Node.required=[];
assert.equal(diffContracts(before,contracts(changed,'seller'))[0].change,'changed','changes in referenced required fields detected');
assert.equal(diffContracts(before,contracts(spec,'performance')).length,2,'same operationId in a different family never aliases');
const broken=structuredClone(spec);broken.paths['/synthetic'].post.requestBody.content['application/json'].schema.$ref='#/missing';
assert.throws(()=>contracts(broken,'seller'),/Unresolved reference/);
assert.equal(diffContracts(before,[])[0].removal_proven,false,'missing path alone never proves removal');
assert.deepEqual(diffContracts(before,before),diffContracts(before,before),'deterministic pinned input');
const secured=structuredClone(spec) as any;
secured.security=[{ApiKey:[]}];secured.components.securitySchemes={ApiKey:{type:'apiKey',in:'header',name:'Api-Key'},Bearer:{type:'http',scheme:'bearer'}};
const bearer=structuredClone(secured);bearer.security=[{Bearer:[]}];
assert.equal(diffContracts(contracts(secured,'seller'),contracts(bearer,'seller'))[0].change,'changed','inherited authorization changes detected');
const keyHeader=structuredClone(secured);keyHeader.components.securitySchemes.ApiKey.name='Changed-Key';
assert.equal(diffContracts(contracts(secured,'seller'),contracts(keyHeader,'seller'))[0].change,'changed','referenced authorization definition changes detected');
const local=structuredClone(secured);local.paths['/synthetic'].post.security=[];
assert.equal(diffContracts(contracts(secured,'seller'),contracts(local,'seller'))[0].change,'changed','local security overrides inherited authorization');
const unresolved=structuredClone(secured);unresolved.security=[{Missing:[]}];
assert.throws(()=>contracts(unresolved,'seller'),/Unresolved security scheme/);
console.log('PASS Ozon diff family identity, refs, recursive/composed schemas and explicit absence');
