import sys,json,pathlib,subprocess,hashlib,datetime,os
stage=pathlib.Path('/opt/marketplace-mcp/release-closure-20261001/final-contract-finance/'+sys.argv[1][:12]+'');base=stage.parent.parent
run=lambda *args:subprocess.check_output(args,text=True).strip()
prod=json.loads(run('docker','inspect','marketplace-mcp-router-1'))[0];image=json.loads(run('docker','image','inspect',prod['Image']))[0]
assert prod['Id']=='c4c5d9d769cd093753105e3073b3a2e4bade29d5767414368f701b0f2cd777b5' and prod['Image']=='sha256:df5059c568ae3566f14c21e96268792d02496b90ae29646c059b318459cd6c7d'
labels=prod['Config'].get('Labels',{});compose=pathlib.Path(labels['com.docker.compose.project.config_files']);rollback=base/'rollback/router-ffc7ef2.tar'
archive_hash=hashlib.file_digest(rollback.open('rb'),'sha256').hexdigest();assert archive_hash=='a27c133b01ed6bb354283c686502dd3a4eab6c66dc8ce9e7630626ab5f491bf1'
env=os.environ.copy();env['CREDENTIALS_DIRECTORY']='/run/credentials/marketplace-mcp.service';subprocess.check_output(['docker','compose','--dry-run','-p','marketplace-mcp','-f',str(base/'rollback/compose-baseline.yaml'),'up','-d','--no-deps','--pull','never','router'],env=env,stderr=subprocess.STDOUT)
identity=json.loads((stage/'candidate-identity.json').read_text());candidate=json.loads(run('docker','inspect',identity['container']))[0]
assert candidate['Id']==identity['container_id'] and candidate['Image']==identity['image_id']
node22=run('docker','exec',identity['container'],'node','-e',"const assert=require('assert/strict');assert.equal(JSON.parse('9007199254740993123',(_k,v,c)=>c.source),'9007199254740993123');console.log(process.version+' lossless reviver PASS')")
logs=subprocess.check_output(['docker','logs','--tail','200',identity['container']],stderr=subprocess.STDOUT);log_errors=[x for x in ['Fatal','FATAL','heap out of memory','ECONNREFUSED','uncaughtException'] if x.encode() in logs]
code="const fs=require('fs');console.log(JSON.stringify({version:JSON.parse(fs.readFileSync('/app/package.json')).version,commit:process.env.GIT_COMMIT??null}));"
source=json.loads(run('docker','exec','marketplace-mcp-router-1','node','-e',code))
r={'at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'hostname':run('hostname'),'production':{'container_id':prod['Id'],'image_id':image['Id'],'RepoTags':image['RepoTags'],'RepoDigests':image.get('RepoDigests',[]),'compose_project':labels['com.docker.compose.project'],'compose_config_path':str(compose),'compose_working_dir':labels['com.docker.compose.project.working_dir'],'compose_sha256':hashlib.file_digest(compose.open('rb'),'sha256').hexdigest(),'embedded_source':source,'manifest_sha256':run('docker','exec','marketplace-mcp-router-1','sha256sum','/app/MARKETPLACE_MCP_MANIFEST.yaml').split()[0],'health':prod['State'].get('Health',{}).get('Status'),'baseline':'ffc7ef2 CONFIRMED'},'rollback':{'status':'READY','archive':str(rollback),'bytes':rollback.stat().st_size,'sha256':archive_hash,'image_id':image['Id'],'RepoDigests':image.get('RepoDigests',[]),'image_preserved':True,'compose_restore_dry_run':'PASS'},'candidate':{'container_id':candidate['Id'],'image_id':candidate['Image'],'state':candidate['State']['Status'],'health':json.loads(run('curl','-sS','--max-time','5','http://127.0.0.1:'+sys.argv[2]+'/health')),'memory_limit':candidate['HostConfig']['Memory'],'memory_events':run('docker','exec',identity['container'],'cat','/sys/fs/cgroup/memory.events'),'node_reviver':node22,'logs_sha256':hashlib.sha256(logs).hexdigest(),'log_error_classes':log_errors},'probe_sha256':{p.name:hashlib.file_digest(p.open('rb'),'sha256').hexdigest() for p in sorted((stage/'probe').glob('*.mjs'))},'production_replaced':False,'deployment':'BLOCKED','post_deploy_smoke':'NOT_RUN'}
(stage/'final-runtime-attestation.json').write_text(json.dumps(r,indent=2));print(json.dumps(r,indent=2))
